clean_workspace: true

git:
  branch: main

builders:
- docker
name: ais_relay_app
docker_name: ais_relay_app
docker_context_dir: .
build_in_docker:
  dockerfile: Dockerfile

extra_jobs:
- name: ais_relay_stunnel
  docker_name: ais_relay_stunnel
  docker_context_dir: stunnel
  build_in_docker:
    dockerfile: Dockerfile
